google-lifesciences: True
google-lifesciences-region : 'us-central1'
use-conda: True
jobs: 150
preemption-default: 5
preemptible-rules: ["fastp=5", "bwa_map=5","merge_bams=5","dedup=5","bam2gvcf=10","create_db_mapfile=5","gvcf2DB=5","DB2vcf=5","filterVcfs=5","sort_gatherVcfs=5","qc_check_fai=5","qc_vcftools_individuals=5","qc_subsample_snps=5","qc_plink=5","qc_admixture=5","qc_generate_coords_file=5","qc_qc_plots=5", "collect_sumstats=2"]
default-resources: ["machine_type=n2-standard", "disk_mb=512000"]

