import pandas as pd
import os
include: "common.smk"
configfile: "config/config.yaml"

samples = pd.read_table(config["samples"], sep=",", dtype=str).replace(' ', '_', regex=True)
REFGENOME = samples['refGenome'].unique().tolist()

rule all:
    input:
        expand("results/{ref_name}/mk/{prefix}_mk_table.tsv", refGenome=REFGENOME, prefix=config['final_prefix'])



rule split_samples:
    """
    Splits sample sheet to make ingroup and outgroup files
    """
    output:
        exclude = "results/mk/{prefix}_exclude.txt",
        outgroups = "results/mk/{prefix}_ougroups.txt"
    run:
        out_df = samples[["BioSample", "SampleType"]]
        out_df.drop_duplicates("BioSample", inplace=True)
        exclude =out_df[~out_df.SampleType.isin(["ingroup", "outgroup"])].BioSample
        outgroups = out_df[out_df.SampleType.isin(["outgroup"])].BioSample
        exclude.to_csv(output[0], index=False, sep="\t", header=False)
        outgroups.to_csv(output[1], index=False, sep="\t", header=False)

rule degenotate:
    """
    Runs degenotate to compute MK tables
    """
    input:
        vcf = "results/{prefix}_clean_snps.vcf.gz",
        genome = "results/mk/{ref_name}.fasta",
        gff = "results/mk/{ref_name}.gff",
        exclude = "results/mk/{prefix}_exclude.txt",
        outgroups = "results/mk/{prefix}_ougroups.txt"
    output:
        "results/mk/{prefix}_mk_table.tsv"
    params:
        delim = "space"
    log:
        "logs/mk/{prefix}_degenotate.txt"
    conda:
        "envs/mk.yml"
    shell:
        """
        if [ -s {input.exclude} ]
        then
            degenotate.py --overwrite -a {input.gff} -g {input.genome} -u {input.outgroups} -e {input.exclude} -d {params.delim} -o "results/{wildcards.refGenome}/mk/{wildcards.prefix}_degen_raw" -v {input.vcf}
        else
            degenotate.py --overwrite -a {input.gff} -g {input.genome} -u {input.outgroups} -d {params.delim} -o "results/{wildcards.refGenome}/mk/{wildcards.prefix}_degen_raw" -v {input.vcf}
        fi
        cp results/{wildcards.refGenome}/mk/{wildcards.prefix}_degen_raw/mk_table.tsv {output}
        """