###
# fastq2bam rules
##

# fastq download
get_fastq_pe:
  threads: 8


# index reference
index_ref:
  threads: 1

# fastp program
fastp:
  threads: 8


# bwa mapping
bwa_map:
  threads: 31

# sort bam with picard's SortSam tool
sort_bam:
    threads: 4

#merge bams
merge_bams:
  threads: 2

# mark duplicates with picard's MarkDuplicates
dedup:
  threads: 31

# calculate BAM summaries with samtools and picard
bam_sumstats:
  threads: 1

bedtools:
  threads: 1

# Sentieon tools
sentieon_map:
  machine_type: "n2d-standard-32"
  threads: 31


sentieon_dedup:
  machine_type: "n2d-standard-32"
  threads: 31


sentieon_haplotyper:
  machine_type: "n2d-standard-32"
  threads: 31


sentieon_combine_gvcf:
  machine_type: "n2d-standard-32"
  threads: 31


###
# Intervals workflow
###

# preprocess genome, create intervals
# picard's create CreateSequenceDictionary, samtools faidx
process_ref:
  threads: 1

# custom python algo to create intervals
create_db_intervals:
  threads: 1

create_gvcf_intervals:
  threads: 1

## Callable sites workflow

# genmap map
genmap:
  threads: 10

genmap_sort:
  threads: 1

compute_d4:
  threads: 4

merge_d4:
  threads: 1

callable_bed:
  threads: 1

###
# bam2vcf workflows
###

# gatk HaplotypeCaller
bam2gvcf:
  threads: 1
# gatk GenomicsDBImport
gvcf2DB:
  threads: 1
# gatk GenotypeGVCFs
DB2vcf:
  threads: 1
# gatk filterVcfs
filterVcfs:
  threads: 1
# gatk GatherVcfs
gatherVcfs:
  threads: 1
# vcftools program
vcftools:
  threads: 1
# plink
plink:
  threads: 5
admixture:
  threads: 1
